# Generated by Django 3.0.5 on 2020-05-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=24)),
                ('full_name', models.CharField(max_length=255)),
                ('t_binding', models.CharField(max_length=24)),
                ('t_dry_remainder', models.CharField(max_length=24)),
                ('t_luster_degree', models.CharField(max_length=24)),
                ('t_solvent', models.CharField(max_length=24)),
                ('t_drying_time', models.CharField(max_length=36)),
                ('t_packaging', models.CharField(max_length=36)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('small_photo', models.ImageField(upload_to='photos/%Y/%m/')),
                ('big_photo', models.ImageField(upload_to='photos/%Y/%m/')),
                ('publicate', models.BooleanField()),
            ],
        ),
    ]
