# Generated by Django 3.0.5 on 2020-05-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='big_photo',
            field=models.ImageField(height_field=400, upload_to='photos/%Y/%m/', width_field=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='small_photo',
            field=models.ImageField(height_field=300, upload_to='photos/%Y/%m/', width_field=200),
        ),
    ]
