# Generated by Django 3.0.5 on 2020-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0002_auto_20200505_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='t_expence',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='t_mass_per_gallon',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='t_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='big_photo',
            field=models.ImageField(blank=True, height_field=400, upload_to='photos/%Y/%m/', width_field=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='small_photo',
            field=models.ImageField(blank=True, height_field=300, upload_to='photos/%Y/%m/', width_field=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='t_binding',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='article',
            name='t_dry_remainder',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='article',
            name='t_drying_time',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='article',
            name='t_luster_degree',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='article',
            name='t_packaging',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='article',
            name='t_solvent',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
