# Generated by Django 3.0.5 on 2020-05-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0003_auto_20200506_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='small_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/'),
        ),
    ]
